# -*- coding: utf-8 -*-
"""
/***************************************************************************
 XYZ_Importer
                                 A QGIS plugin
 Import multiple XYZ Files from Echosounder at once
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-04-01
        copyright            : (C) 2022 by Max Ramstorfer
        email                : maximilianramstorfer@kabsi.at
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load XYZ_Importer class from file XYZ_Importer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .xyz_importer import XYZ_Importer
    return XYZ_Importer(iface)
